version: "3.9"
services:

  microservice:
    build:
      dockerfile: ./deploy/Dockerfile
      context: ../
    container_name: gh-example
    image: gh-example
    restart: always
    environment:
      POSTGRES_HOST: database
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - database
    ports:
      - "8080:8080"

  database:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init.sh